# Generated by Django 5.0.6 on 2024-06-13 13:54

from django.db import migrations

def create_default_home(apps, schema_editor):
    Home = apps.get_model('rajath', 'Home')
    Home.objects.create(
        name="Rajath T",
        greetings_1="Hello",
        greetings_2="guys",
        picture="picture/advert2.png"  # Ensure this path matches your MEDIA_ROOT configuration
    )

def create_about_object(apps, schema_editor):
    About = apps.get_model('rajath', 'About')  # Adjust 'app_name' to your actual app name
    Profile = apps.get_model('rajath', 'Profile')
    # Create the About object
    about_instance = About.objects.create(
        heading="Hi there, I am Rajath Thaliyadath",
        career="Masters in Engineering Student",
        description="I am currently pursuing my studies at Macquarie University in Australia, focusing on furthering my knowledge and skills in computer science. Previously, I gained valuable experience as a Python Django developer at QBurst Technologies for a year and a half, where I honed my expertise in web development and software engineering. I hold a Bachelor's degree in Computer Science from LBS College of Engineering, Kasaragod, Kerala, where I laid the foundation for my career in technology with a strong academic background and hands-on project experience.",
        profile_img="profile/blue-preview.png"  # Adjust to the path relative to your MEDIA_ROOT
    )
    Profile.objects.create(
        about=about_instance,
        social_name="github",
        link="https://github.com/RajathT2000"
    )
    Profile.objects.create(
        about=about_instance,
        social_name="facebook",
        link="https://www.facebook.com/rajath.t.3"
    )
    Profile.objects.create(
        about=about_instance,
        social_name="twitter",
        link="https://github.com/RajathT2000"
    )

def create_category_and_skills(apps, schema_editor):
    Category = apps.get_model('rajath', 'Category')
    Skills = apps.get_model('rajath', 'Skills')

    # Create Category objects
    category1 = Category.objects.create(name="Programming Languages")
    category2 = Category.objects.create(name="Web Development")

    # Create Skills objects
    Skills.objects.create(category=category1, skill_name="Python")
    Skills.objects.create(category=category1, skill_name="C")
    Skills.objects.create(category=category1, skill_name="C#")
    Skills.objects.create(category=category2, skill_name="Django")
    Skills.objects.create(category=category2, skill_name="REST API")

def create_portfolios(apps, schema_editor):
    Portfolio = apps.get_model('rajath', 'Portfolio')

    Portfolio.objects.create(name="Certificates",
                             image="portfolio/work3.jpg",
                             link="portfolio/work4.jpg")
    

class Migration(migrations.Migration):

    dependencies = [
        ('rajath', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_home),
        migrations.RunPython(create_about_object),
        migrations.RunPython(create_category_and_skills),
        migrations.RunPython(create_portfolios)
    ]
