# Generated by Django 5.0.6 on 2024-06-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rajath', '0002_auto_20240613_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='pdf',
            field=models.FileField(default='certificates/Rajath_Build_15_AR.pdf', upload_to='portfolio/'),
        ),
    ]
