# Generated by Django 5.0.6 on 2024-06-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rajath', '0003_portfolio_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(default='picture/certificate_cover.JPEG', upload_to='pictures/')),
                ('pdf', models.FileField(default='certificates/Rajath_Build_15_AR.pdf', upload_to='certificates/')),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='link',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='pdf',
        ),
    ]
