# Generated by Django 5.0.6 on 2024-06-17 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rajath', '0004_certificates_remove_portfolio_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='rajath.about'),
        ),
    ]
